version: '3'
services:
  mysql:
    build: ./mysql
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d  # init用のsql配置用
    image: mysqlapp
    container_name: mysqlapp
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
